language: python
python:
  - '2.6'
  - '2.7'
  - '3.2'
  - '3.3'
install:
  - 'pip install -r requirements.txt'
script:
  - find flemming | grep .py$ | xargs ./venv/bin/pyflakes
  - find flemming | grep .py$ | xargs ./venv/bin/pep8 --max-line-length=120
  - nosetests --cover-branches --with-coverage --cover-min-percentage=100 --cover-package=flemming
