language: python
python:
  - '2.7'
  - '3.0'
  - '3.1'
  - '3.2'
  - '3.3'
  - '3.4'
install:
  - 'pip install -r requirements.txt'
script:
  - find fleming | grep .py$ | grep -v __init__.py | xargs pyflakes
  - find fleming | grep .py$ | xargs pep8 --max-line-length=120
  - nosetests --cover-branches --with-coverage --cover-min-percentage=100 --cover-package=fleming
